BEGIN;

DROP TABLE IF EXISTS  CASCADE;

CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    username VARCHAR (30) NOT NULL
);

CREATE TABLE paraposts (
    id SERIAL PRIMARY KEY NOT NULL,
    parapost TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

COMMIT;